name: super_enum_demo
version: 0.0,1

description: A simple linter test
environment:
  sdk: ">=2.4.0 <3.0.0"
dependencies:
  meta: ^1.1.8
  super_enum: ^0.4.2
 
dev_dependencies:
  super_enum_generator: ^0.5.0
  build_runner:  
  test: ^1.12.0
  lint: ^1.1.1
  effective_dart: ^1.2.1
  pedantic: ^1.9.0